config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  get 'posts/update'
  get 'posts/delete'
  match "/contact", to: "pages#contact", via: :get
  get "/about", to: "pages#about"
  root "pages#index"
  resources :users
  resources :posts
  #resources :sessions, only: [:new,:create,:destroy]
  get "/login", to: "sessions#new"
   get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, length: {maximum: 255}
	validates :user_id, presence: true
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

	has_many_attached :posts
    has_one_attached :avatar
    validates_presence_of :email, :username
    validates_uniqueness_of :email, :username
    validates :password, length: {minimum: 6, maximum: 39}
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :update

    #validates_format_of :email, message: 'The e-mail format is not correct!'
    validates :username, :password, format: { with: /\A[0-9a-zA-Z_.\- ]+\Z/, message: "Only alphanumeric characters, spaces and -_."}
    validates :username, length: {maximum: 30}

    before_create {self.email = email.downcase}
	before_create {self.username = username.downcase}

    attr_accessor :remember_token
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns the hash digest of the given string.
	def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

  # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
      # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
        if remember_digest.nil?
            false
        else
            BCrypt::Password.new(remember_digest).is_password?(remember_token)
        end
  end
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@users = User.all
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	#@user = User.all
 	#@post = @users.collect { |user| user.posts }.flatten
 	@post = Post.includes(:user)
 	@post.user = current_user
  end

  def new
  	@post = Post.new
  end
  def create 
  	@post = Post.new(postParams)
  if @post.save
    flash[:success] = "Post successfully added"
    redirect_to posts_path(@post)
  else
    render 'new'
  end
  end
  def show
  	@post = Post.find(params[:id])
  end

  def update
  end

  def delete
  end
  def postParams
    params.require(:post).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create 
		login = params[:session][:login]
		if login.include? "@"
			user = User.find_by_email(login)
		else
			user = User.find_by_username(login)
		end
    if user && user.authenticate(params[:session][:password])
      sign_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user

		else
			flash[:error] = "Invalid name or password"
			render "new"

		end
	end

	def new 
	end

	def destroy 
		sign_out if signed_in?
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new

	end

	def create
		@user  = User.new(user_params)
		if @user.save
			sign_in @user
			redirect_to @user
		else
			render :new
		end

	end

	def edit
		@user = User.find(params[:id])


	end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user 
		else
			render 'edit'
		end
	end
	
	def destroy
	    sign_out
	    @user = User.find(params[:id]).destroy
			redirect_to users_url



	end
	def user_params 
		params.require(:user).permit(:username, :email,:password, :avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def pretty_title(title)
		#"| " + title unless title.nil? 
		title.nil? ? "Instagram " : "| " + title
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


	def sign_in(user)
		session[:user_id] = user.id
	end


	def signed_in?
		!current_user.nil?

	end
	 # Remembers a user in a persistent session.


	  def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
	  end


	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find(session[:user_id])
		 elsif (user_id = cookies.signed[:user_id])
    		user = User.find_by(id: user_id)
    		if user && user.authenticated?(cookies[:remember_token])
    			sign_in user
    			@current_user = user
    		end
		end
	end
	 # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
	def sign_out
		forget(current_user)
		session[:user_id] = nil
		@current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram <%= pretty_title(@title)%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<%= @title = "Homepage" %>
<h1>Welcome to Instagram!</h1>
<%if signed_in?%>
<h2><%= current_user.username%></h2>
  <li><%= link_to current_user.username, "/users/#{current_user.id}" %></li>
  <li><%= link_to "edit", edit_user_path(current_user) %></li>
  <li><%= link_to "delete", current_user, method: :delete,
                                  data: { confirm: "Are you sure?" } %></li>



<%end%>

app/views/partials/_header.html.erb
<ul>
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <a href="/about">About</a>
      </li>
      <li>
        <a href="/contact">Contact</a>
      </li>
      
        <%if signed_in? %>
        <li>
          
        
          <%= link_to "logout", logout_path, method: :delete, data: { confirm: "Are you sure?"} %></li>
          <%else%>
          <li>
          <%= link_to "login", login_path %></li>
          

      </li>
      <%end%>
    </ul>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/index.html.erb
<ul>
<% @post.each do |post| %>
  <li>
    <%= post.body %>
    <%= post.user.id %>
    <%= post.user.name %>
  </li>
<% end %>
</ul>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<% if @post.errors %>
<ul>
    <% @post.errors.full_messages.each do |m| %>
    <li><%= m %></li>
    <% end %>
</ul>
    <% end %>

<%= f.text_field :body, placeholder: "Your text..." %>
<%= f.submit :submit %>
<%end%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update user profile</h1>
<%= form_for @user do |f| %>
<% if @user.errors %>
<ul>
    <% @user.errors.full_messages.each do |m| %>
    <li><%= m %></li>
    <% end %> 
</ul>
    <% end %>

<%= f.text_field :username, placeholder: "new username" %>
<%= f.text_field :email, placeholder: "new email" %>
<%= f.password_field :password, placeholder: "new password" %>
<%= f.file_field :avatar%>
<%= f.submit :submit %>

<% end %>

app/views/users/index.html.erb
<ul>

	<% @users.each do |user| %>
	<li><%= link_to user.username, "/users/#{user.id}" %></li>
	<li><%= link_to "edit", edit_user_path(current_user) %></li>
	<li><%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %><% end %> </li>

	<% end %>
	
</ul>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<% if @user.errors %>
<ul>
    <% @user.errors.full_messages.each do |m| %>
    <li><%= m %></li>
    <% end %>
</ul>
    <% end %>

<%= f.text_field :username, placeholder: "username" %>
<%= f.text_field :email, placeholder: "email" %>
<%= f.password_field :password, placeholder: "password" %>
<%= f.file_field :avatar%>
<%= f.submit :submit %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h2><%= @user.email %></h2>

<% if @user.avatar.attachment.nil? %>
	<img src="https://www.bsn.eu/wp-content/uploads/2016/12/user-icon-image-placeholder-300-grey.jpg">

<% else %>
	<%= image_tag @user.avatar %>
	
<% end %>